### PR TITLE
inverting icons

### PR DESCRIPTION
**Pull request by tjulien-ledger**
Signed-off-by: tjulien-ledger <thomas.julien@ledger.com>

### CODE REVIEW

**Review by apaillier-ledger — APPROVED** [review]
OK

**Comment by jleni** [comment]
These changes break CI on our side..

I understand that you may not be running CI when doing your PRs but later it can be a problem to integrate them upstream.

**Comment by apaillier-ledger** [comment]
Hello @jleni, the Zemu tests have already been fixed in the commits following the merge of this PR into main.

**Comment by jleni** [comment]
Yes, we would prefer these PRs to go upstream, run CI, etc..
Committing changes directly to main without any CI, tests or review is definitely not ideal or a good practice.

**Pull request merged**
